spring.application.name=admin-dashboard


spring.datasource.url=jdbc:postgresql://dpg-d8hsrqi8qa3s73dr2860-a.oregon-postgres.render.com:5432/admin_dashboard_jxi4
spring.datasource.username=admin_user
spring.datasource.password=Jk9WvcQiXmEQRA1QwWqwV5ZV6aEn7tCM
spring.sql.init.mode=always

spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Root logging level
logging.level.root=INFO

# Your application package
logging.level.com.transaction.dashboard=DEBUG

# Spring logs
logging.level.org.springframework=INFO

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n

logging.level.org.hibernate.SQL=ERROR
logging.level.org.hibernate.orm.jdbc.bind=ERROR